name: 'Update README with Random Haiku'
description: 'Updates the README with a fresh haiku by updating the URL timestamp to avoid cache.'
author: 'Chinmay Sonawane'
runs:
  using: 'composite'
  steps:
    - run: |
        TIMESTAMP=$(date +%s)
        sed -i "s|https://chinmay29hub-haiku-readme.vercel.app/api[^)]*t=[0-9]*|https://chinmay29hub-haiku-readme.vercel.app/api?theme=catppuccin_mocha\&type=vertical\&border=true\&t=$TIMESTAMP|" README.md
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add README.md
        git commit -m "Update haiku timestamp" || echo "No changes to commit"
        git push
      shell: bash
