name: Sync Rollback with Main

on:
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This fetches all history for all branches

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout rollback branch
      run: git checkout rollback

    - name: Ensure rollback is up-to-date with main
      run: |
        # Ensure we are on the rollback branch
        git checkout rollback
        
        # Set user info for commits
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Merge main into rollback
        git merge origin/main --no-ff -m "Merge main into rollback"

    - name: Push changes to rollback branch
      run: git push origin rollback

    - name: Confirm sync
      run: echo "Rollback branch has been successfully updated with main."
