name: Update README with Random Haiku

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s|https://chinmay29hub-haiku-readme.vercel.app/api[^)]*t=[0-9]*|https://chinmay29hub-haiku-readme.vercel.app/api?theme=catppuccin_mocha\&type=vertical\&border=true\&t=$TIMESTAMP|" test.md
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add test.md
          git commit -m "Update haiku timestamp" || echo "No changes to commit"
          git push